# Form implementation generated from reading ui file 'parameters_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Stat_parameters_window(object):
    def setupUi(self, Stat_parameters_window):
        Stat_parameters_window.setObjectName("Stat_parameters_window")
        Stat_parameters_window.resize(373, 149)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Stat_parameters_window.sizePolicy().hasHeightForWidth())
        Stat_parameters_window.setSizePolicy(sizePolicy)
        Stat_parameters_window.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Stat_parameters_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=Stat_parameters_window)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Stat_parameters_window)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label = QtWidgets.QLabel(parent=Stat_parameters_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(parent=Stat_parameters_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Stat_parameters_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Stat_parameters_window)
        self.buttonBox.accepted.connect(Stat_parameters_window.accept) # type: ignore
        self.buttonBox.rejected.connect(Stat_parameters_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Stat_parameters_window)

    def retranslateUi(self, Stat_parameters_window):
        _translate = QtCore.QCoreApplication.translate
        Stat_parameters_window.setWindowTitle(_translate("Stat_parameters_window", "Choose Parameter"))
        self.label_2.setText(_translate("Stat_parameters_window", "Time Interval (min)"))
        self.label.setText(_translate("Stat_parameters_window", "Choose a parameter for the test"))
        self.comboBox.setItemText(0, _translate("Stat_parameters_window", "Migration Persistence (Autocorrelation)"))
        self.comboBox.setItemText(1, _translate("Stat_parameters_window", "Speed"))
        self.comboBox.setItemText(2, _translate("Stat_parameters_window", "MSD"))
        self.comboBox.setItemText(3, _translate("Stat_parameters_window", "Directionality Ratio"))
