# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        # Set Main Window
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        # Set central widget
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Horizontal Layout
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.splitter = QtWidgets.QSplitter()
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)

        # Tree widget - layout right
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setAcceptDrops(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setHeaderLabels(["Opened Files"])
        self.horizontalLayout.addWidget(self.treeWidget)

        # Stacked widget - layout left
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.splitter.addWidget(self.treeWidget)
        self.splitter.addWidget(self.stackedWidget)

        self.horizontalLayout.addWidget(self.splitter)

        self.treeWidget.hide()
        MainWindow.setCentralWidget(self.centralwidget)

        # Statusbar
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Tool bar
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setAcceptDrops(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        # Menu bar
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAnalyse = QtWidgets.QMenu(parent=self.menuBar)
        self.menuAnalyse.setObjectName("menuAnalyse")
        self.menuStatistics = QtWidgets.QMenu(parent=self.menuBar)
        self.menuStatistics.setObjectName("menuStatistics")
        self.menuPlot = QtWidgets.QMenu(parent=self.menuBar)
        self.menuPlot.setObjectName("menuPlot")
        MainWindow.setMenuBar(self.menuBar)
        
        self.actionNew_File = QtGui.QAction(parent=MainWindow)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionOpen_File = QtGui.QAction(parent=MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(parent=MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        
        self.actionUndo = QtGui.QAction(parent=MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(parent=MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtGui.QAction(parent=MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(parent=MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(parent=MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtGui.QAction(parent=MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSelect_All = QtGui.QAction(parent=MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        
        self.actionAutocorrelation = QtGui.QAction(parent=MainWindow)
        self.actionAutocorrelation.setObjectName("actionAutocorrelation")
        self.actionSpeed = QtGui.QAction(parent=MainWindow)
        self.actionSpeed.setObjectName("actionSpeed")
        self.actionMSD = QtGui.QAction(parent=MainWindow)
        self.actionMSD.setObjectName("actionMSD")
        self.actionDirectionality_Ratio = QtGui.QAction(parent=MainWindow)
        self.actionDirectionality_Ratio.setObjectName("actionDirectionality_Ratio")
        
        self.actionTrajectories = QtGui.QAction(parent=MainWindow)
        self.actionTrajectories.setObjectName("actionTrajectories")

        self.actionTtest = QtGui.QAction(parent=MainWindow)
        self.actionTtest.setObjectName("actiontTtest")
        self.actionANOVA = QtGui.QAction(parent=MainWindow)
        self.actionANOVA.setObjectName("actionANOVA")
        
        self.toolBar.addAction(self.actionNew_File)
        self.toolBar.addAction(self.actionOpen_File)
        self.toolBar.addAction(self.actionSave)
        
        self.toolBar.addSeparator()

        self.toolBar.addAction(self.actionAutocorrelation)
        self.toolBar.addAction(self.actionMSD)
        self.toolBar.addAction(self.actionSpeed)
        self.toolBar.addAction(self.actionDirectionality_Ratio)
        self.toolBar.addSeparator()
        
        self.toolBar.addAction(self.actionTrajectories)
        self.toolBar.addSeparator()

        self.toolBar.addAction(self.actionTtest)
        self.toolBar.addAction(self.actionANOVA)


        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addSeparator()
        
        self.menuAnalyse.addAction(self.actionAutocorrelation)
        self.menuAnalyse.addAction(self.actionSpeed)
        self.menuAnalyse.addAction(self.actionMSD)
        self.menuAnalyse.addAction(self.actionDirectionality_Ratio)
        self.menuAnalyse.addSeparator()
        self.menuAnalyse.addAction(self.actionp_value)

        self.menuStatistics.addAction(self.actionTtest)
        self.menuStatistics.addAction(self.actionANOVA)
        
        self.menuPlot.addAction(self.actionTrajectories)
        
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuAnalyse.menuAction())
        self.menuBar.addAction(self.menuStatistics.menuAction())
        self.menuBar.addAction(self.menuPlot.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cell Migration"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAnalyse.setTitle(_translate("MainWindow", "Analyse"))
        self.menuStatistics.setTitle(_translate("MainWindow", "Statistics"))
        self.menuPlot.setTitle(_translate("MainWindow", "Plot"))
        self.actionNew_File.setText(_translate("MainWindow", "New File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))
        self.actionAutocorrelation.setText(_translate("MainWindow", "Autocorrelation"))
        self.actionSpeed.setText(_translate("MainWindow", "Speed"))
        self.actionMSD.setText(_translate("MainWindow", "MSD "))
        self.actionDirectionality_Ratio.setText(_translate("MainWindow", "Directionality Ratio"))
        self.actionp_value.setText(_translate("MainWindow", "p-value"))
        self.actionTrajectories.setText(_translate("MainWindow", "Trajectories"))
        self.actionTtest.setText(_translate("MainWindow", "T test"))
        self.actionANOVA.setText(_translate("MainWindow", "ANOVA"))
