# Form implementation generated from reading ui file 'configuration_autocorrelation_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConfigurationAutocorrelationWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(371, 211)

        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")

        self.formLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        self.time_interval = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.time_interval.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.time_interval.setObjectName("time_interval")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.time_interval)

        self.lineEdit_time_interval = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_time_interval.setObjectName("lineEdit_time_interval")
        self.lineEdit_time_interval.setText("10")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_time_interval)
        
        self.n_time_points = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.n_time_points.setObjectName("n_time_points")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.n_time_points)
        
        self.lineEdit_n_time_points = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_n_time_points.setObjectName("lineEdit_n_time_points")
        self.lineEdit_n_time_points.setText("40")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_n_time_points)
        
        self.n_tracks = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.n_tracks.setObjectName("n_tracks")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.n_tracks)
        
        self.lineEdit_n_tracks = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_n_tracks.setObjectName("lineEdit_n_tracks")
        self.lineEdit_n_tracks.setText("20")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_n_tracks)
        
        self.n_plot_points = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.n_plot_points.setObjectName("n_plot_points")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.n_plot_points)
        
        self.lineEdit_n_plot_points = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_n_plot_points.setObjectName("lineEdit_n_plot_points")
        self.lineEdit_n_plot_points.setText("6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_n_plot_points)
        
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.formLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.buttonBox)

        self.verticalLayout.addWidget(self.formLayoutWidget)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Parameter Configuration"))
        self.time_interval.setText(_translate("Dialog", "Time Interval (min)"))
        self.n_time_points.setText(_translate("Dialog", "Number of time points"))
        self.n_tracks.setText(_translate("Dialog", "Number of tracks (cells)"))
        self.n_plot_points.setText(_translate("Dialog", "Number of points for the plot"))
